spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_ant?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

    defer-datasource-initialization: true
    open-in-view: false
    generate-ddl: true
    show-sql: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: ${app.oauth.google.client-id}
            client-secret: ${app.oauth.google.client-secret}
            scope:
              - email
              - profile
            redirect-uri: ${app.oauth.google.redirect-uri}

          kakao:
            client-id: ${app.oauth.kakao.client-id}
            client-secret: ${app.oauth.kakao.client-secret}
            scope:
              - profile_nickname
            authorization-grant-type: authorization_code
            redirect-uri: ${app.oauth.kakao.redirect-uri}
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: ${app.oauth.naver.client-id}
            client-secret: ${app.oauth.naver.client-secret}
            scope:
              - name
            authorization-grant-type: authorization_code
            redirect-uri: ${app.oauth.naver.redirect-uri}
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

app:
  oauth:
    google:
      client-id: 196466839765-a3pbrgao7ncferhj69i5d01nj9f8qhj8.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: http://localhost:8080/login/oauth2/code/google
    kakao:
      client-id: 37f7c42ee8f631c1154652f0d62bebe9
      client-secret: P7hIVw6e98dp7RFSMCWhX322MmIVMOHl
      redirect-uri: http://localhost:8080/login/oauth2/code/kakao
    naver:
      client-id: 59itXn3Xv5ttJkZOI8Yn
      client-secret: lpbHZaYDqQ
      redirect-uri: http://localhost:8080/login/oauth2/code/naver